### ISSUE TITLE
Нет документации по развертыванию

### ISSUE THREAD

**Issue by yaliilyaya** [eprikazchikov/thunder#151]
Опиши, пожалуйста, как развернуть твой проект, а так же маленький пример. 

Люди которые не сильно углублялись в разработку на С++ просто не в курсе, как разворачивается проект, особенно как он билдиться. 

В самом лучшем случае, это должно быть видео на ютубе, где с нуля ты раазвернёш движок, откроешь(импортнёш ) существующий проект и его сбилдишь в готовое решение.

**Comment by eprikazchikov** [comment]
Hi Iliya, Building instructions are available [here](https://github.com/eprikazchikov/thunder/blob/master/README.md) and [here](https://github.com/eprikazchikov/thunder-doc/blob/master/basics/install.rst).

The people who don't want to build the project from source files are able to use the [Releases](https://github.com/eprikazchikov/thunder/releases) page.

Sample projects are available in separate [repository](https://github.com/eprikazchikov/thunder-samples)

Unfortunately, I have no time, good script and a good pronouncement to write 'Getting started' video, but it's a good idea and I will do this soon.

**Comment by yaliilyaya** [comment]
Спасибо!
