### ISSUE TITLE
Platform: Linux missed libraries

### ISSUE THREAD

**Issue by eprikazchikov** [eprikazchikov/thunder#199]
## Description

Missed libraries on Linux platform

## Prerequisites

Editor and Build application is compiled

## Steps to Reproduce

1. Make `ldd ./WorldEditor`

### Expected behavior:

All dependencies are resolved

### Actual behavior:

Some of the libraries are missed in the list

```
libfbxsdk.so => not found
libfreetype-editor.so => not found
libphysfs-editor.so => not found
libglfw-editor.so => not found
libicui18n.so.56 => not found
libicuuc.so.56 => not found
libicudata.so.56 => not found
```

### Reproducibility:

Constant

## Versions

2019.3

## Additional Information

N/A

**Comment by marcotaranta** [comment]
Hello, can I have that issue?

**Comment by eprikazchikov** [comment]
Sure, I'm a bit help to you =) the problem is related to RPATH for the "Engine" library.

**Comment by marcotaranta** [comment]
You ship those shared objects with the WorldEditor executable in the same folder? If so I'll need to change the build script to change the RPATH to "." after the executable has been built.

**Comment by eprikazchikov** [comment]
> If so I'll need to change the build script to change the RPATH to "." after the executable has been built.
Not really. You would need to change the build script to change RPATH during the linking step. You can use WorldEditor target as an example. The shared libraries are placed in the lib directory at the up level.

**Comment by marcotaranta** [comment]
You're right, I was thinking about the chrpath tool to change it, but there's the linker's flag for setting the rpath. I will take a look on that!

**Comment by marcotaranta** [comment]
Okay, I found the problem with the *-editor.so and fixed it.
The libICU libraries aren't shipped with the final package, I think you need another issue to deal with building and/or shipping ICU.
The libfbxsdk.so library is shipped in the same directory as the binaries (bin), but the rpath is searching in the libraries path (lib), so what should I do? Change the rpath to include the current folder (".")? Or deploy the libfbxsdk.so in the libraries folder (lib)?

**Comment by eprikazchikov** [comment]
Nice. FBX lib must be in lib dir. It seems like my miss. Regarding ICU as far as I remember it's a part of qt binaries and can be copied. But need to check.

**Comment by marcotaranta** [comment]
Ok, I'll copy fbx and icu libraries to the /lib directory.
